services:
  api:
    build:
      context: ./go-api
    container_name: go-chess-api
    env_file:
      - path: .env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./go-chess-react
    container_name: go-chess-frontend
    depends_on:
      - api
    ports:
      - "5173:80"
